[control_plane]
control-plane ansible_host=100.58.211.235 private_ip=172.31.6.230

[workers]
worker-1 ansible_host=18.204.4.45 private_ip=172.31.11.31
worker-2 ansible_host=3.239.70.171 private_ip=172.31.15.64

[k8s_nodes:children]
control_plane
workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/labsuser.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
